### PR TITLE
Added number formatting for 'hold' figures

### PR DESCRIPTION
**Pull request by tagawa**
Note: The `Intl.NumberFormat` method is from the Internationalization API which now has pretty wide browser support: http://caniuse.com/#feat=internationalization

### CODE REVIEW

**Comment by tagawa** [comment]
crypto-number-formatting

**Comment by Daven-** [comment]
looks good, thanks!

**Comment by tagawa** [comment]
Thanks @Daven-. I really like your app, so simple but helpful. I have a couple more ideas for small tweaks, when I get time.

**Comment by Daven-** [comment]
Thank you! lmk if I can help with any.

**Pull request merged**
